export const GAME_CONFIG = {
  TILE_SIZE: 32,
  ANIMATION: {
    WALK_FRAME_RATE: 8,
    MOVEMENT_DURATION: 200,
    TYPEWRITER_DELAY: 30
  },
  UI: {
    BAR_WIDTH: 200,
    BAR_HEIGHT: 20,
    UI_Y: 20,
    PADDING: 20
  },
  PLAYER: {
    DEFAULT_SCALE: 0.5,
    INITIAL_GRID_X: 25,
    INITIAL_GRID_Y: 15,
    INITIAL_GRID_X_SECOND: 15,
    INITIAL_GRID_Y_SECOND: 10
  },
  COMBAT: {
    PROJECTILE_DISTANCE: 200,
    PROJECTILE_SPEED: 1000,
    PROJECTILE_SCALE: 0.05,
    POOP_SCALE: 0.05,
    MANA_COST: 10,
    EXP_GAIN_MOVE: 10,
    EXP_GAIN_CHEW: 15
  },
  WORLD: {
    STONE_FREQUENCY: 0.05,
    RANDOM_SPEECH_CHANCE: 0.15,
    MOVEMENT_SPEECH_CHANCE: 0.3
  },
  COLORS: {
    BACKGROUND: '#92C16D',
    HEALTH_BAR: 0xF24E5C,
    MANA_BAR: 0x6A9F4D,
    BAR_BACKGROUND: 0x3E372E,
    TEXT_PRIMARY: '#353535',
    TEXT_WHITE: '#FFFFFF',
    TEXT_GOLD: '#FFD700',
    TEXT_RED: '#F24E5C',
    CONTROLS_TEXT: '#8B6A4E'
  }
} as const